substitutions:
  name: jk-bms
  device_description: "Monitor and control a JK-BMS v11 via bluetooth"
  external_components_source: github://rabbit3dcustom/esphome-jk-bms@main
  esp_ip: 192.168.1.244
  # Please use "JK02_24S" if you own a old JK-BMS < hardware version 11.0 (hardware version >= 6.0 and < 11.0)
  # Please use "JK02_32S" if you own a new JK-BMS >= hardware version 11.0 (f.e. JK-B2A8S20P hw 11.XW, sw 11.26)
  # Please use "JK04" if you have some old JK-BMS <= hardware version 3.0 (f.e. JK-B2A16S hw 3.0, sw. 3.3.0)
  protocol_version: JK02_32S

  tx_pin_uart_0: GPIO22
  rx_pin_uart_0: GPIO23
  talk_pin_rs485: GPIO21

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-jk-bms"
    version: 2.0.0

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s
  # components: [jk_rs485_sniffer, jk_rs485_bms]

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

  # Optional manual IP
  manual_ip:
    static_ip: ${esp_ip}
    gateway: 192.168.1.1
    subnet: 255.255.255.0

ota:
  platform: esphome

logger:
  level: DEBUG

# If you don't use Home Assistant please remove this `api` section and uncomment the `mqtt` component!
api:

#web_server:
#  port: 80

uart:
  - id: uart_0
    baud_rate: 115200
    rx_buffer_size: 500
    tx_pin: ${tx_pin_uart_0}
    rx_pin: ${rx_pin_uart_0}

jk_rs485_sniffer:
  - id: sniffer0
    protocol_version: ${protocol_version}
    rx_timeout: 500ms
    uart_id: uart_0
    talk_pin: ${talk_pin_rs485}

jk_rs485_bms:
  - id: bms1
    rs485_address: 0x01
    jk_rs485_sniffer_id: sniffer0
    update_interval: 100s

binary_sensor:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms1
    status_balancing:
      name: "${name} status balancing"
    status_charging:
      name: "${name} status charging"
    status_discharging:
      name: "${name} status discharging"
    status_heating:
      name: "${name} status heating"
#    online_status:
#      name: "${name} online status"

number:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms1
    cell_request_charge_voltage_time:
      name: "${name} cell request charge volt time"
    cell_request_float_voltage_time:
      name: "${name} cell request float volt time"

# sensor:
#   - platform: jk_bms_ble
#     uart1_protocol_number:
#       name: "${name} uart1 protocol number"
#     uart2_protocol_number:
#       name: "${name} uart2 protocol number"

switch:
  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms1
    charging:
      name: "${name} charging"

text_sensor:
  - platform: uptime
    name: "Uptime"
    # expand: true
    update_interval: 5s

  - platform: jk_rs485_bms
    jk_rs485_bms_id: bms1
    errors:
      name: "${name} errors"
    operation_status:
      name: "${name} operation status"
    info_device_password:
      name: "${name} info_device_password"
    info_software_version:
      name: "${name} info_software_version"
    info_vendorid:
      name: "${name} info vendorid"
    info_hardware_version:
      name: "${name} info hardware version"
    info_device_name:
      name: "${name} info device name"
